name: calc_imc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 2.19.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
